Assignment2 David Cabornero
FacultadInformatica-LinkedData/Curso2021-2022-ODKG pull request #55
Opened 2021-09-26 22:04 UTC by DCabornero

2021-10-03 21:35 UTC, ocorcho requested changes

2021-10-03 21:35 UTC, ocorcho commented on Assignment2/DCabornero.ttl
> +            vocab:atTime  "2010-06-12T12:00:12"^^xsd:date.
Should be dateTime

2021-10-04 21:50 UTC, ocorcho commented
Assignment 2 ok. Now @dgarijo can check assignment 4.

2021-10-06 14:36 UTC, dgarijo commented
Missing 7.1, 7.2 and 7.3 in rdflib. Other than that it looks good.

2021-10-21 07:39 UTC, merged