Assignment 2 by Julio Nevado
FacultadInformatica-LinkedData/Curso2021-2022-ODKG pull request #58
Opened 2021-09-27 13:45 UTC by julionevadodel

2021-10-03 21:35 UTC, ocorcho requested changes

2021-10-03 21:35 UTC, ocorcho commented on Assignment2/turtle_JulioNevado.ttl
> +                 foaf:atTime "2010-06-12T 12:00:12" .
There should be datatypes

2021-10-06 09:33 UTC, dgarijo requested changes
Looks ok, but it has an error and it's missing how to accomplish the same thing in rdflib (see review)

2021-11-15 11:27 UTC, dgarijo commented
No changes have been implemented, so I am closing this PR.

2021-11-15 11:27 UTC, closed without merging