Assignment 1 and 2
FacultadInformatica-LinkedData/Curso2021-2022-ODKG pull request #73
Opened 2021-09-29 08:26 UTC by Rlongares

Done

2021-10-03 21:29 UTC, ocorcho requested changes

2021-10-03 21:29 UTC, ocorcho commented on Assignment2/rlongares-RicardoMaríaLongaresDíez.ttl
> +									:atTime "2010-06-12T12:00:12".
datatypes should be included

2021-10-04 21:52 UTC, ocorcho commented
Ok. Although I will have to work a bit on it in order to solve the conflict

2021-11-15 11:28 UTC, dgarijo commented
Branch has conflicts, so I am closing it up

2021-11-15 11:28 UTC, closed without merging