Assignment1
FacultadInformatica-LinkedData/Curso2021-2022-ODKG pull request #75
Opened 2021-09-29 16:05 UTC by elia-alonso-rueda

I have added my information to the file.

2021-10-03 17:02 UTC, ocorcho commented on Assignment2/Elia-elia.alonsoru.ttl
> +			:atTime 	"2010-06-12T12:00:12"xsd:date .
It should be dateTime, but just accepted.

2021-10-03 17:03 UTC, ocorcho requested changes

2021-10-03 17:03 UTC, ocorcho commented on Assignment2/Elia-elia.alonsoru.ttl
> +		:includes 	:Computer 101 .
This is wrong. No blank space should be there between Computer and 101. Same with the sensor

2021-11-15 11:28 UTC, dgarijo commented
Branch has conflicts, @ocorcho please review.

2021-11-15 11:41 UTC, merged